name: rdkit-thesis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip
  - rdkit=2025.03.3
  - pytorch=2.7.1
  - torchaudio=2.7.1
  - torchvision=0.22.1
  - pytorch-lightning=2.5.2
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - umap-learn
  - ipykernel
  - jupyterlab
  - pycairo
  - reportlab
  - pybind11
  - numba
  - lightning
  - lightning-utilities
  - optree
  - pip:
      - faiss-cpu==1.11.0.post1
      - wandb==0.21.0
      - multilabel-knn==0.0.2
